const DishName=[
    { key:0,
    imgsrc:"https://tse1.mm.bing.net/th?id=OIP.4o-XcBAer1qDcTi-IKya0QHaEK&pid=Api&rs=1&c=1&qlt=95&w=215&h=120",
    title:"South Indian",
    sname:"Dosa",
    link:"https://www.google.com",
    },
    {key:1,
    imgsrc:"https://tse1.mm.bing.net/th?id=OIP.Sb_e1OqhvwrBftVMe0NF7AHaJ4&pid=Api&rs=1&c=1&qlt=95&w=80&h=107",
    title:"Chinese",
    sname:"Noodles",
    link:"https://www.google.com",
    },
    {key:2,
    imgsrc:"https://tse1.mm.bing.net/th?id=OIP.XZmgDPJC-SlK8FOXnQyZEQHaFc&pid=Api&rs=1&c=1&qlt=95&w=168&h=123",
    title:"Desert",
    sname:"Cake",
    link:"https://www.google.com",
    },
    {key:3,
    imgsrc:"https://tse4.mm.bing.net/th?id=OIP.Uy9SdiH_soLIGuJ0W8rrIAHaLH&pid=Api&P=0&w=300&h=300",
    title:"Indian",
    sname:"Curry",
    link:"https://www.google.com",
    },{key:4,
    imgsrc:"https://tse4.mm.bing.net/th?id=OIP.yB21NyihyIhQK3SQ7kiF1AHaEo&pid=Api&P=0&w=297&h=186",
    title:"Muti Grain",
    sname:"Bread",
    link:"https://www.google.com",
    }
    ]
    export default DishName;